# Generated by Django 3.2.9 on 2021-11-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uname', models.TextField(unique=True)),
                ('mail', models.TextField()),
                ('password', models.TextField()),
                ('creationdate', models.DateField(auto_now_add=True)),
                ('userid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
