# Generated by Django 3.2.9 on 2021-11-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.TextField()),
                ('mail', models.TextField()),
                ('password', models.TextField()),
                ('date', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserPublic',
        ),
    ]
