# Generated by Django 3.2.9 on 2021-11-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20211117_1526'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateUser',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='date',
            new_name='creationdate',
        ),
    ]
